name: Build TWRP Exynos 990

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean and Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Initialize Repo and Sync
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          export PATH=~/bin:$PATH

          mkdir workspace
          cd workspace
          
          # Sửa twrp-11.0 thành twrp-11
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-11 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Sync TWRP Source & Build
        run: |
          # Đưa device tree vào workspace
          git clone ${{ github.server_url }}/${{ github.repository }} device/samsung/exynos990-common
          
          # Chạy lệnh build chuẩn của Android
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch omni_exynos990-eng || lunch twrp_exynos990-eng
          mka recoveryimage -j$(nproc)
