name: Makefile CI

on:
  push:
    branches: [ "android-12.1" ]
  pull_request:
    branches: [ "android-12.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure

    - name: Install dependencies
      run:       
      . build/envsetup.sh
      lunch twrp_x1s-eng
      mka recoveryimage

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
