name: Makefile CI

on:
  push:
    branches: [ "android-12.1" ]
  pull_request:
    branches: [ "android-12.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run:  make

    - name: Build TWRP
        run: |
          cd workspace
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch omni_<mã_máy>-eng
          mka recoveryimage -j$(nproc)
